feat(rag): correctly forwards some errors
The RAG service would return 500 errors, which is totally opaque to the
user.
My llama-server showed:

```
 send_error: task id = 1120, error: input (1060 tokens) is too large to process. increase the physical batch size (current batch size: 1024)
```

so the error was pretty clear. Let's forward it to the user so he can
understand what's wrong and act on it